# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lucca Augusto
email: lucca@luccaaugusto.xyz
copyright: FDP Corporations. Todos os direitos reservados.
description: >- # this means to ignore newlines until "baseurl:"
    Uai, meu site e blog pessoal sô, da uma olhada ai.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luccaaugusto.xyz" # the base hostname & protocol for your site, e.g. http://example.com
github_username: lrr68
url_pds: "https://pds.luccaaugusto.xyz"
url_port: "https://portfolio.luccaaugusto.xyz"
url_mal: "https://myanimelist.net/profile/luccaugusto"
url_letterboxd: "https://letterboxd.com/luccaugusto/"
url_colab55: "https://www.colab55.com/@luccaugusto"
user_mal: "luccaugusto"
user_spot: "luccaugusto"
user_letterboxd: "luccaugusto"
url_spot: "https://open.spotify.com/user/luccaugusto"
url_linkedin: "https://www.linkedin.com/in/lucca-augusto-santos-b66416195"
url_orkut: "https://www.orkut.br.com/MainProfile?uid=2736677"
wish_amazon: "https://www.amazon.com.br/hz/wishlist/ls/YICR8H5942MX?ref_=wl_share"

# Colab55 coupons
coupon5off: Z6R2F5
c55url5off: https://www.colab55.com?aff=z6r2f5
c55url10conto: https://www.colab55.com/via/@luccaugusto

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Treat my posts as collections so i dont have that stupid date on url
collections:
  blog:
    output: true
  ded:
    output: true
  tablaturas:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
