name: CI
run-name: Jekyll Site deployment
on:
  push:

jobs:
  build:
    runs:
      using: 'node16'
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3

      - name: Initialize the ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Jekyll prerequisites
        run: sudo apt-get install ruby-full build-essential zlib1g-dev

      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Build the website
        run: ./build.sh

      - name: Scan the host key
        run: mkdir -p ~/.ssh/ && ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}

      - name: Deploy the website
        run: >-
          rsync -avx --delete --exclude '.ssh' _site/ $DEPLOY_USERNAME@$DEPLOY_SERVER:/var/www/luccaaugusto.xyz/html/
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
